// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wzctanmkchbcgrfwsimc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind6Y3Rhbm1rY2hiY2dyZndzaW1jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0NzQxODgsImV4cCI6MjA2NTA1MDE4OH0.xMIDYc27MK_vWbt-wqfzMBO1ApU7biQXFSHHdGh2ZYU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});